name: DecomposeTransformer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - transformers
  - scipy
  - huggingface_hub
  - scikit-learn
  - spacy
  - notebook
  - matplotlib
  - pip
  - pip:
    - datasets
