name: DecomposeTransformer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - pytorch-cuda=12.4
  - transformers
  - scipy
  - huggingface_hub
  - scikit-learn
  - spacy
  - notebook
  - matplotlib
  - pip
  - tqdm
  - papermill
  - pip:
    - datasets
    - colorama
    - pyrootutils